### PR TITLE
Fix Settings issues; closes #32

### LINKED ISSUE #32: Card mode should properly render only FINOS Projects
Currently the card mode shows a mix of projects and members.

Please fix [here](https://github.com/finos/finos-landscape/blob/master/settings.yml#L43-L52) to only display FINOS projects.

### PR DESCRIPTION
**Pull request by dankohn**
Signed-off-by: Dan Kohn <dan@dankohn.com>

### CODE REVIEW

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is accepted successfully, we ask all our open source contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement).

Having reviewed our contributor list, we require a CLA for the following people : (@dankohn).

If you need help obtaining a CLA, please read the [Requirements for Contributions](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) section of our CLA wiki or email [help@finos.org](mailto:help@finos.org) with your questions.

Thanks once again for your contribution. Let us work with you to make the CLA process quick, easy and efficient so we can move forward with reviewing and accepting your pull request.

_cc_ **@finos-admin**

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is accepted successfully, we ask all our open source contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement).

Having reviewed our contributor list, we require a CLA for the following people : (@dankohn).

If you need help obtaining a CLA, please read the [Requirements for Contributions](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) section of our CLA wiki or email [help@finos.org](mailto:help@finos.org) with your questions.

Thanks once again for your contribution. Let us work with you to make the CLA process quick, easy and efficient so we can move forward with reviewing and accepting your pull request.

_cc_ **@finos-admin**

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is accepted successfully, we ask all our open source contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement).

Having reviewed our contributor list, we require a CLA for the following people : (@dankohn).

If you need help obtaining a CLA, please read the [Requirements for Contributions](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) section of our CLA wiki or email [help@finos.org](mailto:help@finos.org) with your questions.

Thanks once again for your contribution. Let us work with you to make the CLA process quick, easy and efficient so we can move forward with reviewing and accepting your pull request.

_cc_ **@finos-admin**

**Comment by mindthegab** [comment]
@maoo can you please whitelist @dankohn and @caniszczyk to start with and other LF folks that will work on the landscape? Will raise metadata issue.

**Pull request merged**
