### PR TITLE
Adding devops mutualization to landscape

### PR DESCRIPTION
**Pull request by maoo**

### CODE REVIEW

**Comment by toshaellison** [comment]
Per our conversation this should not have the "incubating" status & border but rather one that says "FINOS Special Interest Group" or "Special Interest Group".

**Comment by maoo** [comment]
@toshaellison - can you please review the preview? https://deploy-preview-76--finos-landscape.netlify.app/

Maybe the grey colour is a bit off? Feel free to send me the RGB code of the colour to set and/or lmk if I can merge.

TY!

**Comment by toshaellison** [comment]
@maoo Can you use the aqua color from the Applications header for SIGs. I fear grey might be perceived as "inactive". Thank you.

**Comment by maoo** [comment]
@toshaellison yes, but I didn't understand where to get the colour from. Feel free to screenshot it, and I'll take it from there, or provide a URL. TY!

**Comment by maoo** [comment]
@toshaellison - it's done, WDYT? https://deploy-preview-76--finos-landscape.netlify.app/

**Comment by toshaellison** [comment]
Looks great, thanks @maoo

**Pull request merged**
