### PR TITLE
additional_repos and custom homepage_urls

### PR DESCRIPTION
**Pull request by maoo**
We're adding `additional_repos` entries for projects having multiple github repositories.

We're also rendering out homepage URLs for all FINOS projects that want to provide a custom one, otherwise we will default to their (first) GitHub repository homepage.

### CODE REVIEW

**Comment by dankohn** [comment]
It's fine that you're using a metadata tool to go from some other format to landscape.yml, but I encourage you to start with small changes to confirm the syntax. I also recommend installing landscapeapp locally so that you can have a much faster debug cycle. Directions: https://github.com/cncf/landscapeapp#installing-locally

**Comment by maoo** [comment]
TY @dankohn . We actually didn't change much on this PR, but indentation doesn't match (I assume that the landscape bot updates the `landscape.yml` file when the website is deployed). I could try to force your same indentation before pushing the file, that would solve the issue.

Agreed on installing landscape locally, I'll work on it.

**Comment by dankohn** [comment]
Yes, YAML is infamously finicky about indentation. Every night, CNCF-Bot updates processed_landscape.yml by fetching updated external info and runs `yq` to reformat landscape.yml as well.

Please emulate this syntax https://github.com/lfph/lfph-landscape/blob/master/landscape.yml#L39-L48 and start with just one item.

**Comment by maoo** [comment]
@dankohn - I've added YQ and there are less differences, but still, the majority of file differences are indentation, see https://github.com/finos/finos-landscape/pull/44/files 

I'll play with it locally. Thanks.

**Comment by maoo** [comment]
> Build failed because of:
> Membership category "FINOS Members" does not have corresponding category in landscape.yml

@dankohn - I managed to fix the syntax of `additional_repos`, but now it complains about `FINOS Members`, any idea why? Since I haven't changed anything on categories, I wanted to check with you first, as I'd like to avoid breaking the card mode settings you've worked on last week. TIA!

**Comment by dankohn** [comment]
I believe you're using a tool to pull in your membership and auto-generate part or all of landscape.yml? That's OK, but the tool needs some adjustment. landscapeapp is expecting a single category for membership and then subcategories for type of member. See here: https://github.com/finos/finos-landscape/blob/master/landscape.yml#L330

Also, best practices in YAML is to quote values when they include punctuation characters. Running `yq` loads the YAML, alphabetizes, and then re-emits it in canonical form.

You'll want your tool to do something similar or else you're going to have really noisy diffs like on this branch.

Please feel free to ping me at https://slack.cncf.io if you want additional details.

**Comment by maoo** [comment]
Thanks @dankohn - I'll check your link to fix categories and sub-categories for our members.

Re. format, we already use `yq` to format the auto generated landscape.yml: `yq r landscape.yml > ${LANDSCAPE_PATH}`

**Comment by dankohn** [comment]
Something about your use of `yq` is off because the end of the diff in this PR shows you incorrectly removing quotes from all the Crunchbase URLs.

**Comment by maoo** [comment]
> Build failed because of:
> Integration tests have failed for unclear reasons. Please run locally for more info and/or ask for help on #landscapers-help on slack.cncf.io

I've run `yf` and `yo` locally, all went fine. Netlify is failing on tests, with the following error:

```
4:55:20 PM:  FAIL  specs/main.spec.js (17.981s)
4:55:20 PM:   ● Normal browser › Filtering by organization › Checking we don't see Alloy when filtering by organization Finos
4:55:20 PM:     Element "//div[contains(@class, 'mosaic')]//*[text()='Alloy']" was not supposed to be found.
4:55:20 PM: 
4:55:20 PM:       158 |     test(`Checking we don't see ${project.name} when filtering by organization ${otherProject.organization}`, async function() {
4:55:20 PM:       159 |       await page.goto(`${appUrl}/organization=${otherOrganizationSlug}&format=card-mode`);
4:55:20 PM:     > 160 |       await expect(page).not.toHaveElement(`//div[contains(@class, 'mosaic')]//*[text()='${project.name}']`);
4:55:20 PM:           |                              ^
4:55:20 PM:       161 |     });
4:55:20 PM:       162 |     close();
4:55:20 PM:       163 |   }, 6 * 60 * 1000);
4:55:20 PM: 
4:55:20 PM:       at Object.<anonymous> (specs/main.spec.js:160:30)
4:55:20 PM:           at runMicrotasks (<anonymous>)
```

@dankohn - any idea what I'm doing wrong here?

**Comment by AndreyKozlov1984** [comment]
I've updated a test so the build passes, still the question is why sometimes we have a 'FINOS' organization and sometimes it is a lowercase 'finos'

**Comment by AndreyKozlov1984** [comment]
Here is the latest issue, crunchbase claims that an organization is 'Finos', and I see a lot of FINOS entries, any chance to always use "Finos" ?

**Pull request merged**
