### PR TITLE
adding regulation innovation SIG logo

### PR DESCRIPTION
**Pull request by aitana16**

### CODE REVIEW

**Comment by maoo** [comment]
https://deploy-preview-79--finos-landscape.netlify.app @aitana16 @toshaellison - ready for review.

**Comment by toshaellison** [comment]
Location looks good, thank you! It should have the blue SIG border and "lifecycle" label.

**Comment by maoo** [comment]
> Location looks good, thank you! It should have the blue SIG border and "lifecycle" label.

Great catch @toshaellison !

Fixed on https://github.com/finos/metadata/commit/471ddc54bb75632b97f528ed487514c03c755fe6 - should update the preview shortly; if/when fixed, I'll proceed with the merging.

**Comment by toshaellison** [comment]
Looks good, thanks!

**Pull request merged**
