### PR TITLE
Add FINOS states as project relations

### PR DESCRIPTION
**Pull request by maoo**
Each item in `landscape.yml` now has a `project:` field which can be `archived`, `incubating` or `active`.

In `settings.yml` I've configured the entries.

Part of https://github.com/finos/finos-landscape/issues/47

Here is a cleaner diff of the proposed changes - https://github.com/finos/finos-landscape/compare/pr52?expand=1

### CODE REVIEW

**Comment by maoo** [comment]
> You need to install with yarn not npm. Please follow the directions in the landscapeapp Readme

That's what I normally do, but if I run `yo` I get
```
Usage Error: Couldn't find autoprefixer@npm:9.8.6 in the currently installed PnP map - running an install might help

$ yarn run [--inspect] [--inspect-brk] <scriptName> ...
```

So I try to run `yarn run build`, and I get:
```
yarn run v1.22.4
$ npm run latest; npm config set scripts-prepend-node-path true; export PROJECT_PATH="$PWD"; npm explore interactive-landscape -- npm run build

> lfdl-interactive-landscape@1.0.0 latest /Users/m/w/projects/landscape/finos-landscape
> npm install interactive-landscape@latest

npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "patch:": patch:puppeteer@5.0.0#./puppeteer.patch
```

Regarding the Netlify build, it's failing due to `FATAL: Project Alloy has been added to incubating category but does not belong to FINOS`. Maybe I made some mistakes in settings.yml? See https://github.com/finos/finos-landscape/blob/staging/settings.yml#L33-L53

TY @dankohn !

**Comment by AndreyKozlov1984** [comment]
Hi, regarding a local install, the problem is still that you try to use old scripts and old aliases which we do not support anymore.

We have new aliases in the landscapeapp readme, here is what we do during the development without aliases at all:
` cd landscapeapp
  export PROJECT_PATH=../finos-landscape
  yarn
  yarn open:src
`
Assuming that you have `landscapeapp` and `finos-landscape` folders in the same folder.

**Comment by maoo** [comment]
Great catch @AndreyKozlov1984 , thank you! I did have the old aliases defined in my bash config. I've added a https://github.com/finos/finos-landscape/blob/staging/setup.sh (to invoke as `. ./setup.sh` so that I don't need to rely anymore on bash profile configuration; assuming that absolute paths can be turned into relative ones, it may be a good addition to landscape to avoid other people stumbling on this issue, wdyt?

Re. the pending issue, I managed to reproduce it locally:
```
git clone -b pr52 git@github.com:finos/finos-landscape.git
cd finos-landscape
yf
```

I still get `FATAL: Project Alloy has been added to incubating category but does not belong to FINOS` , these are the changes - https://github.com/finos/finos-landscape/compare/pr52?expand=1 ; any idea what I'm doing wrong? TY!

**Comment by maoo** [comment]
Dup of https://github.com/finos/finos-landscape/pull/56 - closing.

**Pull request closed without merging**
