### PR TITLE
Project badges

### PR DESCRIPTION
**Pull request by maoo**
One item in `landscape.yml` (`Alloy` project) now has a `project:` field which can be `archived`, `incubating` or `active`.

In `settings.yml` I've configured the 3 states.

Part of #47

### CODE REVIEW

**Comment by maoo** [comment]
Netlify fails with `2:44:15 PM: FATAL: Project Alloy has been added to incubating category but does not belong to FINOS
`

**Comment by maoo** [comment]
Thanks @dankohn ! I've checked the preview on https://deploy-preview-56--finos-landscape.netlify.app/ but the `Alloy` logo looks like before (see l.finos.org for comparison), whereas I'd have expected the logo to be overlaid with `FINOS incubating` at the bottom, just like it's shown on https://landscape.cncf.io/ for some logos (see example below).

Screenshot 2020-08-25 at 18 55 32

Is there anything else that needs to be done in order to overlay our logos?

**Comment by dankohn** [comment]
Please add 100% of your categories, including the one that Alloy is in, to settings.yml. The expectation is that every card should be visible in both landscape and card mode, but you're missing categories.

**Comment by maoo** [comment]
@dankohn - I added the `project` field to all our project items in `landscape.yml` , but I still don't see the project logos being overlaid with badges - https://deploy-preview-56--finos-landscape.netlify.app/ . Any idea why? Thank you!

**Comment by dankohn** [comment]
Please create a category in settings.yml for every category in landcape.yml.

**Comment by maoo** [comment]
> Please create a category in settings.yml for every category in landcape.yml.

I've checked all categories in `landscape.yml`. The only ones missing in `settings.yml` are [FINOS](https://github.com/finos/finos-landscape/blob/staging/landscape.yml#L346) (not sure if it's used anywhere or needed by the landscapeapp) and [FINOS Members](https://github.com/finos/finos-landscape/blob/staging/landscape.yml#L357), although members are displayed in card mode, see https://github.com/finos/finos-landscape/blob/staging/settings.yml#L56 .

**Comment by dankohn** [comment]
Please create the missing categories in order to see the project logos with badges. You can always remove them before merging this branch.

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is accepted successfully, we ask all our open source contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement).

Having reviewed our contributor list, we require a CLA for the following people : (@AndreyKozlov1984).

If you need help obtaining a CLA, please read the [Requirements for Contributions](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) section of our CLA wiki or email [help@finos.org](mailto:help@finos.org) with your questions.

Thanks once again for your contribution. Let us work with you to make the CLA process quick, easy and efficient so we can move forward with reviewing and accepting your pull request.

_cc_ **@finos-admin**

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is accepted successfully, we ask all our open source contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement).

Having reviewed our contributor list, we require a CLA for the following people : (@AndreyKozlov1984).

If you need help obtaining a CLA, please read the [Requirements for Contributions](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) section of our CLA wiki or email [help@finos.org](mailto:help@finos.org) with your questions.

Thanks once again for your contribution. Let us work with you to make the CLA process quick, easy and efficient so we can move forward with reviewing and accepting your pull request.

_cc_ **@finos-admin**

**Comment by AndreyKozlov1984** [comment]
image

**Comment by dankohn** [comment]
@finos-admin @maoo Please mark @AndreyKozlov1984 as being covered under the Linux Foundation CCLA because he's a contractor.

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is accepted successfully, we ask all our open source contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement).

Having reviewed our contributor list, we require a CLA for the following people : (@AndreyKozlov1984).

If you need help obtaining a CLA, please read the [Requirements for Contributions](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) section of our CLA wiki or email [help@finos.org](mailto:help@finos.org) with your questions.

Thanks once again for your contribution. Let us work with you to make the CLA process quick, easy and efficient so we can move forward with reviewing and accepting your pull request.

_cc_ **@finos-admin**

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is accepted successfully, we ask all our open source contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement).

Having reviewed our contributor list, we require a CLA for the following people : (@AndreyKozlov1984).

If you need help obtaining a CLA, please read the [Requirements for Contributions](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) section of our CLA wiki or email [help@finos.org](mailto:help@finos.org) with your questions.

Thanks once again for your contribution. Let us work with you to make the CLA process quick, easy and efficient so we can move forward with reviewing and accepting your pull request.

_cc_ **@finos-admin**

**Comment by maoo** [comment]
Thanks @AndreyKozlov1984 ! The new landscape looks exactly how we wanted it.

Apparently we were missing a `big_picture_order` field in the settings.

I'm waiting for approval before merging this PR.

We'll also add you to the list of approved contributors, to avoid the CLA bot complaining about your PRs.

Thank you!

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is accepted successfully, we ask all our open source contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement).

Having reviewed our contributor list, we require a CLA for the following people : (@AndreyKozlov1984).

If you need help obtaining a CLA, please read the [Requirements for Contributions](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) section of our CLA wiki or email [help@finos.org](mailto:help@finos.org) with your questions.

Thanks once again for your contribution. Let us work with you to make the CLA process quick, easy and efficient so we can move forward with reviewing and accepting your pull request.

_cc_ **@finos-admin**

**Comment by maoo** [comment]
@finos-cla-bot[bot] check

**Comment by finos-admin** [comment]
The cla-bot has been summoned, and re-checked this pull request!

**Pull request merged**
